### ISSUE TITLE
Misc to-do

### ISSUE THREAD

**Issue by karenword** [carpentries/instructor-training-bonus-modules#9]
- [x] Modify content here and/or in handbook to accurately describe cohost ability to move between breakouts
- [x] Enhance instructions to host for introducing the workshop to create 'what did we do' opportunities in part 2
* Emergency instructions
* How to DM coinstructor
* CoC text
- [x] Clarify Zoom instructions: 
* add "assign host to someone else" at end
* "adjust who can share their screen" vs limits
* last person can close breakout rooms
- [x] Add instructions for cuckoo timer or other timekeeping to activity text
- [x] Ad role reminders to activity text
- [x] Debrief instructions
- [x] Add instructions for assigning a captioner in Zoom

**Comment by karenword** [comment]
Add note regarding time limiting breakouts as a timer alternative to cuckoo (downside = rigid time limit)

**Comment by karenword** [comment]
Look into moving between breakouts for cohosts and participants (latest info)

**Comment by klbarnes20** [comment]
> Look into moving between breakouts for cohosts and participants (latest info)

[Source: Zoom - Managing Breakout Rooms](https://support.zoom.us/hc/en-us/articles/206476313-Managing-Breakout-Rooms
)
**Options for breakout rooms**
After creating the breakout rooms, click Options to view additional breakout rooms options.

Check any options that you would like to use for your breakout rooms.

- **Allow participants to choose room: Participants can select and enter rooms on their own once rooms are launched.** 
- Allow participants to return to the main session at any time: If this option is checked, the participants can move back to the main session from their meeting controls. If this is disabled, they need to wait for the host to end the breakout rooms.
- Automatically move all assigned participants into breakout rooms: Checking this option will move all participants into the breakout rooms automatically. If this option is unchecked, the participants will need to click Join to be added to the breakout room.
- Auto close breakout rooms after () minutes: If this option is checked, the breakout rooms will automatically end after the configured time.
- Notify me when the time is up: If this option is checked, the host will be notified when the breakout room time is up.
- Set Countdown timer: If this option is checked, the participants will be given a countdown of how much time they have left before being returned to the main room.
- Follow the steps below to assign participants to rooms or click Open All Rooms to start the breakout rooms.

**Comment by karenword** [comment]
Maybe take a screenshot of a Zoom + Etherpad side-by-side setup to use in the introduction.
